third_party_settings:
  field_group:
    group_d_subscribe_background:
      label: 'Subscribe background'
    group_d_subscribe_content:
      label: 'Subscribe content'
    group_d_subscribe_info:
      label: 'Subscribe info'
