third_party_settings:
  field_group:
    group_tabs:
      label: Tabs
    group_settings:
      label: Settings
    group_items:
      label: Items
content:
  field_d_p_sbs_items:
    settings:
      title: Paragraph
      title_plural: Paragraphs
