third_party_settings:
  field_group:
    group_d_form_background:
      label: 'Form background'
    group_d_form_content:
      label: 'Form content'
    group_d_form_fields:
      label: 'Form fields'
