third_party_settings:
  field_group:
    group_tabs:
      label: Tabs
    group_settings:
      label: Settings
    group_boxes:
      label: Boxes
content:
  field_d_p_tb_block_reference:
    settings:
      title: Paragraph
      title_plural: Paragraphs
