name: 'Product categories » Taxonomy term » Name'
url_alias: product_categories_taxonomy_term_name
widget:
  config:
    soft_limit_settings:
      show_less_label: 'Show less'
      show_more_label: 'Show more'
