label: 'E-mail body'
description: "Use [download-button] to render download button.\r\n\r\n"
default_value:
  -
    value: "<p>Hi, this is your download link</p>\r\n\r\n<p>The link will be active 24h from now</p>\r\n\r\n<p>[download-button]</p>\r\n\r\n<p>Droopler Team</p>\r\n"
