label: 'Download page message'
description: 'Use [download-button] to render download button.'
default_value:
  -
    value: "<h2>Enjoy Droopler!</h2>\r\n\r\n<p>[download-button]</p>\r\n\r\n<p class=\"additional\">More info how use it on <a href=\"https://droopler.pl/doc\">https://droopler.pl/doc</a>.</p>\r\n"
