label: 'Content: Blog post'
tags:
  description: '[node:field_blog_teaser]'
  title: '[node:title] | [site:name]'
  og_image: '[node:field_blog_media_main_image:entity:field_media_image:responsive_image_2000:url]'
  og_description: '[node:field_blog_teaser]'
