label: 'Content: Content Page'
tags:
  description: '[node:field_teaser_text]'
  title: '[node:title] | [site:name]'
  og_image: '[node:field_teaser_media_image:entity:field_media_image:responsive_image_2000:url]'
  og_description: '[node:field_teaser_text]'
