label: 'Product Images'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        nothing:
          alter:
            text: "<div class=\"slider-container\">\r\n  {{ field_product_image }}\r\n</div>"
      title: 'Product Images'
      arguments:
        nid:
          exception:
            title: All
  attachment_1:
    display_title: Attachment
  block_1:
    display_title: Block
    display_options:
      fields:
        nothing:
          alter:
            text: "<div class=\"slider-container\">\r\n  {{ field_d_product_media }}\r\n</div>"
