label: 'Products list'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
          text_input_required: 'Select any filter and click on Apply to see results'
          bef:
            general:
              secondary_label: 'Advanced options'
            sort:
              advanced:
                collapsible_label: 'Sort options'
          text_input_required_format: full_html
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      sorts:
        search_api_id:
          expose:
            label: 'Newly Added'
        title_1:
          expose:
            label: 'Title Ascending'
        title:
          expose:
            label: 'Title Descending'
      title: Products
  products_list:
    display_title: Products
    display_options:
      display_description: 'Products list with teasers'
