label: 'Blog listing'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: PREVIOUS
            next: NEXT
            first: «
            last: »
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        title:
          separator: ', '
      title: Blog
      arguments:
        tid:
          exception:
            title: All
  page_1:
    display_title: Page
    display_options:
      title: Blog
      arguments:
        tid:
          exception:
            title: All
          title: '{{ arguments.tid }}'
  premium_blog_posts:
    display_title: 'Premium: Blog posts'
    display_options:
      title: Blog
