third_party_settings:
  field_group:
    group_tabs:
      label: Вкладки
    group_settings:
      label: Налаштування
    group_items:
      label: Елементи
content:
  field_d_p_sbs_items:
    settings:
      title: Абзац
      title_plural: Абзаци
