content_access_roles_gids:
  anonymous: 1
  authenticated: 2
  administrator: 3
  d_editor: 4
  call_operator: 5
_core:
  default_config_hash: 7LkiviGITIpniIOOIzpuxR7r4XzqqYN_cwu0fb0kx1M
langcode: ru
content_access_node_type:
  content_page: 'a:3:{s:8:"view_own";a:4:{i:0;s:9:"anonymous";i:1;s:13:"authenticated";i:2;s:13:"administrator";i:3;s:8:"d_editor";}s:4:"view";a:4:{i:0;s:9:"anonymous";i:1;s:13:"authenticated";i:2;s:13:"administrator";i:3;s:8:"d_editor";}s:8:"per_node";i:1;}'
  call_script: 'a:2:{s:8:"view_own";a:3:{i:0;s:13:"call_operator";i:1;s:13:"administrator";i:2;s:8:"d_editor";}s:4:"view";a:3:{i:0;s:13:"call_operator";i:1;s:13:"administrator";i:2;s:8:"d_editor";}}'
