definitions:
  d_demo__engines:
    weight: -45
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
  d_product__products:
    weight: -42
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
  d__blog__d__blog:
    weight: -43
    menu_name: main
    parent: ''
    enabled: true
    expanded: false
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
langcode: ru
