session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    uk: ua
    en: en
    ru: ru
  domains:
    uk: ''
    en: ''
    ru: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
langcode: ru
