session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    ru: ru
    en: en
    uk: uk
  domains:
    ru: ''
    en: ''
    uk: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
langcode: ru
