entity_type_groups:
  node:
    content_page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
    d_product:
      basic: basic
      advanced: advanced
      open_graph: open_graph
