format: full_html
name: 'Колл-центр "Razum Agency"'
mail: admin@razum.agency
linkonly: false
textonly: false
sitestyle: true
simple_address: false
preserve_class: false
advanced:
  incoming: false
  key: xgktdELiy1avV9peyr-coQT3kf9DOwqyy8nk2LFKWRQ
_core:
  default_config_hash: rLKGzzC9TqjbEZiBoiyMpOSyZgldADa5SzvbA2gQDxE
langcode: ru
